pipeline:
  identifier: Build_timekillerj_TechTask_1740583972373
  name: Build tornado-webapp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1740521201589
        repoName: timekillerj/TechTask
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: DockerHub
                    repo: timekillerj/my-tornado-webapp
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: tornado-webapp/Dockerfile
                    context: tornado-webapp
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
