apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tornado-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-tornado-app
  template:
    metadata:
      labels:
        app: my-tornado-app
    spec:
      serviceAccountName: tornado-app-sa
      containers:
      - name: tornado-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8888
        securityContext:
          privileged: false
