apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_HOST: {{ .Values.mongoSecret.mongoHost }}
  MONGO_USER: {{ .Values.mongoSecret.mongoUser }}
  MONGO_PASS: {{ .Values.mongoSecret.mongoPass }}
